### ISSUE TITLE
How to expose this publicly?

### ISSUE THREAD

**Issue by Nowaker** [kapost/cabbage_doc#2]
If I delete `config.authentication = proc do ... end` part from the initializer, I'm getting NoMethodError from authentication.rb:7 (`Configuration.instance.authentication.call(auth, request)`). It seems like authentication is obligatory, while I want this to be exposed publicly. I just want to make sure whether it's a bug, or I'm doing something wrong. Thanks.

```
[rails] 2016-06-08 15:58:00 - NoMethodError - undefined method `call' for nil:NilClass:
[rails]         /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/cabbage_doc-0.0.2/lib/cabbage_doc/authentication.rb:7:in `block in new'
[rails]         /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/cabbage_doc-0.0.2/lib/cabbage_doc/authentication.rb:5:in `tap'
[rails]         /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/cabbage_doc-0.0.2/lib/cabbage_doc/authentication.rb:5:in `new'
[rails]         /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/cabbage_doc-0.0.2/lib/cabbage_doc/web_helper.rb:22:in `auth'
[rails]         /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/cabbage_doc-0.0.2/web/views/authentication.haml:1:in `block in singleton class'
[rails]         /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/cabbage_doc-0.0.2/web/views/authentication.haml:-9:in `instance_eval'
[rails]         /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/cabbage_doc-0.0.2/web/views/authentication.haml:-9:in `singleton class'
[rails]         /home/nowaker/projekty/virtkick/starter/.rvm/gems/ruby-2.2.2/gems/cabbage_doc-0.0.2/web/views/authentication.haml:-11:in `__tilt_34979100'
```

**Comment by Nowaker** [comment]
It seems I totally misunderstood what `config.authentication` is.
